[colors]
draw_bold_text_with_bright_colors = true

[colors.bright]
black = "#b4b4b4"
blue = "#b3d2ff"
cyan = "#c2fefa"
green = "#e3f7a1"
magenta = "#e5bdff"
red = "#f99f92"
white = "#ffffff"
yellow = "#f2e9bf"

[colors.normal]
black = "#000000"
blue = "#6ebaf8"
cyan = "#90fdf8"
green = "#bde97c"
magenta = "#ef88ff"
red = "#f7786d"
white = "#e5e1d8"
yellow = "#efdfac"

[colors.primary]
background = "#1f1f1f"
foreground = "#e5e1d8"

[env]
TERM = "xterm-256color"

[font]
size = 14.0

[font.bold]
family = "IosevkaTerm Nerd Font Mono"
style = "Regular"

[font.bold_italic]
family = "IosevkaTerm Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "IosevkaTerm Nerd Font Mono"
style = "Italic"

[font.normal]
family = "IosevkaTerm Nerd Font Mono"
style = "Regular"

[font.offset]
x = -1

[hints]
alphabet = "jfkdls;ahgurieowpq"

[[hints.enabled]]
command = "xdg-open"
post_processing = true
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)[^\u0000-\u001F\u007F-<>\"\\s{-}\\^⟨⟩`]+"

[hints.enabled.mouse]
enabled = true
mods = "None"

[selection]
save_to_clipboard = true
semantic_escape_chars = ''',│`|:"' ()[]{}<>	'''

[window]
opacity = 0.95

[window.padding]
x = 6
y = 6
