vim.g.mapleader = ' '
vim.g.maplocalleader = ','

require 'config.lazy-bootstrap'
require 'config.options'
require 'config.lsp'
require 'config.keymaps'
require 'config.autocommands'
require 'config.highlights'
require 'config.usercommands'
